data_pipeline_poc:
  target: dev
  outputs:
    dev:
      type: spark
      method: thrift
      host: spark-iceberg
      port: 10000
      user: root
      schema: default
      connect_retries: 3
      connect_timeout: 10
      retry_all: true
      
    prod:
      type: spark
      method: thrift
      host: spark-iceberg
      port: 10000
      user: root
      schema: default
      connect_retries: 3
      connect_timeout: 10
      retry_all: true
